### ISSUE TITLE
can't compile and can't install with opam

### ISSUE THREAD

**Issue by zoggy** [vbmithr/ocaml-websocket#33]
Hello,

version 0.9.3 does not compile with tls 5.0:
````
File "tests/wscat.ml", line 49, characters 4-20:
Error: Unbound value Tls_lwt.rng_init
````
and current version in repository does not compile:
````
File "lib/websocket.ml", line 108, characters 4-16:
Error: Unbound value read_exactly
````
I signaled the second problem here: https://github.com/mirage/ocaml-cohttp/commit/e30f2927f09ab7c67853f0801cda57f48d7d50a6#commitcomment-11742886

I hope there will be new Cohttp/Websocket versions soon, as recent changes in tls/nocrypto/conduit resulted in a nightmare to install cohttp/websocket.

**Comment by vbmithr** [comment]
On 18/06/2015 11:39, Zoggy wrote:
> <https://github.com/mirage/ocaml-cohttp/commit/e30f2927f09ab7c67853f0801cda57f48d7d50a6#commitcomment-11742886>
> 
> I hope there will be new Cohttp/Websocket versions soon, as recent
> changes in tls/nocrypto/conduit resulted in a nightmare to install
> cohttp/websocket.
> 

I'm fixing this right now.

-- 
Vincent

**Comment by vbmithr** [comment]
Fixed in HEAD. An OPAM package is pending for release 2.0.0.

The API has changed, for the better I hope (no more Lwt streams), and the code is IMO of better quality and easier to reason about.
Please test it and report any problem you may have with it.

**Comment by zoggy** [comment]
Damned, I liked the message streams. I will test right now. Thanks!
